default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: database
      user: postgres
      password: nopswd
      port: 5432
      dbname: db1
      schema: dbt_dev
      threads: 1
prod:
  target: prod
  outputs:
    prod:
      type: postgres
      host: database
      user: postgres
      password: nopswd
      port: 5432
      dbname: db1
      schema: dbt_prod
      threads: 1
